create table if not exists public.caepi_datasets (
  id uuid primary key default gen_random_uuid(),
  source_type text not null,
  source_url text not null,
  source_hash text not null,
  status text not null check (status in ('importing','active','archived','failed')),
  total_rows integer not null default 0,
  distinct_cas integer not null default 0,
  ignored_rows integer not null default 0,
  archive_bytes bigint,
  txt_bytes bigint,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.caepi_records (
  id bigint generated by default as identity primary key,
  dataset_id uuid not null references public.caepi_datasets(id) on delete cascade,
  ca text not null,
  data_validade date,
  situacao text,
  fabricante text,
  cnpj text,
  equipamento text,
  descricao text,
  marca text,
  referencia text,
  norma text,
  laudos jsonb,
  raw jsonb not null default '{}'::jsonb,
  record_hash text not null,
  created_at timestamptz not null default now(),
  unique (dataset_id, record_hash)
);

create unique index if not exists caepi_one_active_dataset_idx
  on public.caepi_datasets (status)
  where status = 'active';

create index if not exists caepi_records_lookup_idx
  on public.caepi_records (dataset_id, ca, data_validade desc nulls last, id desc);

create index if not exists caepi_records_ca_idx
  on public.caepi_records (ca);

create index if not exists caepi_datasets_hash_idx
  on public.caepi_datasets (source_hash);

create or replace function public.caepi_activate_dataset(p_dataset_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows integer;
  v_cas integer;
begin
  perform pg_advisory_xact_lock(hashtext('caepi_activate_dataset'));

  select count(*)::integer, count(distinct ca)::integer
    into v_rows, v_cas
  from public.caepi_records
  where dataset_id = p_dataset_id;

  if v_rows < 80000 then
    raise exception 'CAEPI dataset rejeitado: % registros; mínimo 80000', v_rows;
  end if;

  if v_cas < 25000 then
    raise exception 'CAEPI dataset rejeitado: % CAs distintos; mínimo 25000', v_cas;
  end if;

  if not exists (
    select 1
    from public.caepi_datasets
    where id = p_dataset_id
      and status = 'importing'
  ) then
    raise exception 'CAEPI dataset % não está em importing', p_dataset_id;
  end if;

  update public.caepi_datasets
     set status = 'archived'
   where status = 'active'
     and id <> p_dataset_id;

  update public.caepi_datasets
     set status = 'active',
         total_rows = v_rows,
         distinct_cas = v_cas,
         completed_at = now()
   where id = p_dataset_id;
end;
$$;

create or replace function public.caepi_fail_dataset(p_dataset_id uuid, p_error text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.caepi_datasets
     set status = 'failed',
         completed_at = now(),
         metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('error', p_error)
   where id = p_dataset_id
     and status = 'importing';
end;
$$;

revoke all on function public.caepi_activate_dataset(uuid) from public;
revoke all on function public.caepi_fail_dataset(uuid, text) from public;
grant execute on function public.caepi_activate_dataset(uuid) to service_role;
grant execute on function public.caepi_fail_dataset(uuid, text) to service_role;
